/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedExploreRouteRouteImport } from './routes/_authenticated/explore/route'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AuthenticatedExploreIndexRouteImport } from './routes/_authenticated/explore/index'
import { Route as AuthenticatedExploreHospitalsRouteImport } from './routes/_authenticated/explore/hospitals'
import { Route as ApiHospitalsNearbyRouteImport } from './routes/api/hospitals/nearby'
import { Route as ApiHospitalsRecommendRouteImport } from './routes/api/hospitals/recommend'
import { Route as ApiMedicinesIndexRouteImport } from './routes/api/medicines/index'
import { Route as ApiMedicinesIdRouteImport } from './routes/api/medicines/$id'
import { Route as ApiMedicinesBySymptomRouteImport } from './routes/api/medicines/by-symptom'
import { Route as ApiMedicinesSearchRouteImport } from './routes/api/medicines/search'
import { Route as ApiRemindersDailyRouteImport } from './routes/api/reminders/daily'
import { Route as AuthenticatedExploreMedicinesIdRouteImport } from './routes/_authenticated/explore/medicines/$id'
import { Route as AuthenticatedExploreSymptomsNameRouteImport } from './routes/_authenticated/explore/symptoms/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRouteRoute =
  AuthenticatedExploreRouteRouteImport.update({
    id: '/explore',
    path: '/explore',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExploreIndexRoute =
  AuthenticatedExploreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExploreRouteRoute,
  } as any)
const AuthenticatedExploreHospitalsRoute =
  AuthenticatedExploreHospitalsRouteImport.update({
    id: '/hospitals',
    path: '/hospitals',
    getParentRoute: () => AuthenticatedExploreRouteRoute,
  } as any)
const ApiHospitalsNearbyRoute = ApiHospitalsNearbyRouteImport.update({
  id: '/api/hospitals/nearby',
  path: '/api/hospitals/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHospitalsRecommendRoute = ApiHospitalsRecommendRouteImport.update({
  id: '/api/hospitals/recommend',
  path: '/api/hospitals/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicinesIndexRoute = ApiMedicinesIndexRouteImport.update({
  id: '/api/medicines/',
  path: '/api/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicinesIdRoute = ApiMedicinesIdRouteImport.update({
  id: '/api/medicines/$id',
  path: '/api/medicines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicinesBySymptomRoute = ApiMedicinesBySymptomRouteImport.update({
  id: '/api/medicines/by-symptom',
  path: '/api/medicines/by-symptom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicinesSearchRoute = ApiMedicinesSearchRouteImport.update({
  id: '/api/medicines/search',
  path: '/api/medicines/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersDailyRoute = ApiRemindersDailyRouteImport.update({
  id: '/api/reminders/daily',
  path: '/api/reminders/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedExploreMedicinesIdRoute =
  AuthenticatedExploreMedicinesIdRouteImport.update({
    id: '/medicines/$id',
    path: '/medicines/$id',
    getParentRoute: () => AuthenticatedExploreRouteRoute,
  } as any)
const AuthenticatedExploreSymptomsNameRoute =
  AuthenticatedExploreSymptomsNameRouteImport.update({
    id: '/symptoms/$name',
    path: '/symptoms/$name',
    getParentRoute: () => AuthenticatedExploreRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof AuthenticatedExploreRouteRouteWithChildren
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/api/chat': typeof ApiChatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/explore/hospitals': typeof AuthenticatedExploreHospitalsRoute
  '/api/hospitals/nearby': typeof ApiHospitalsNearbyRoute
  '/api/hospitals/recommend': typeof ApiHospitalsRecommendRoute
  '/api/medicines/$id': typeof ApiMedicinesIdRoute
  '/api/medicines/by-symptom': typeof ApiMedicinesBySymptomRoute
  '/api/medicines/search': typeof ApiMedicinesSearchRoute
  '/api/reminders/daily': typeof ApiRemindersDailyRoute
  '/explore/': typeof AuthenticatedExploreIndexRoute
  '/api/medicines/': typeof ApiMedicinesIndexRoute
  '/explore/medicines/$id': typeof AuthenticatedExploreMedicinesIdRoute
  '/explore/symptoms/$name': typeof AuthenticatedExploreSymptomsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/api/chat': typeof ApiChatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/explore/hospitals': typeof AuthenticatedExploreHospitalsRoute
  '/api/hospitals/nearby': typeof ApiHospitalsNearbyRoute
  '/api/hospitals/recommend': typeof ApiHospitalsRecommendRoute
  '/api/medicines/$id': typeof ApiMedicinesIdRoute
  '/api/medicines/by-symptom': typeof ApiMedicinesBySymptomRoute
  '/api/medicines/search': typeof ApiMedicinesSearchRoute
  '/api/reminders/daily': typeof ApiRemindersDailyRoute
  '/explore': typeof AuthenticatedExploreIndexRoute
  '/api/medicines': typeof ApiMedicinesIndexRoute
  '/explore/medicines/$id': typeof AuthenticatedExploreMedicinesIdRoute
  '/explore/symptoms/$name': typeof AuthenticatedExploreSymptomsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRouteRouteWithChildren
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/api/chat': typeof ApiChatRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/_authenticated/explore/hospitals': typeof AuthenticatedExploreHospitalsRoute
  '/api/hospitals/nearby': typeof ApiHospitalsNearbyRoute
  '/api/hospitals/recommend': typeof ApiHospitalsRecommendRoute
  '/api/medicines/$id': typeof ApiMedicinesIdRoute
  '/api/medicines/by-symptom': typeof ApiMedicinesBySymptomRoute
  '/api/medicines/search': typeof ApiMedicinesSearchRoute
  '/api/reminders/daily': typeof ApiRemindersDailyRoute
  '/_authenticated/explore/': typeof AuthenticatedExploreIndexRoute
  '/api/medicines/': typeof ApiMedicinesIndexRoute
  '/_authenticated/explore/medicines/$id': typeof AuthenticatedExploreMedicinesIdRoute
  '/_authenticated/explore/symptoms/$name': typeof AuthenticatedExploreSymptomsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/api/chat'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/explore/hospitals'
    | '/api/hospitals/nearby'
    | '/api/hospitals/recommend'
    | '/api/medicines/$id'
    | '/api/medicines/by-symptom'
    | '/api/medicines/search'
    | '/api/reminders/daily'
    | '/explore/'
    | '/api/medicines/'
    | '/explore/medicines/$id'
    | '/explore/symptoms/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analyze'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/api/chat'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/explore/hospitals'
    | '/api/hospitals/nearby'
    | '/api/hospitals/recommend'
    | '/api/medicines/$id'
    | '/api/medicines/by-symptom'
    | '/api/medicines/search'
    | '/api/reminders/daily'
    | '/explore'
    | '/api/medicines'
    | '/explore/medicines/$id'
    | '/explore/symptoms/$name'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/explore'
    | '/_authenticated/analyze'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/api/chat'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/_authenticated/explore/hospitals'
    | '/api/hospitals/nearby'
    | '/api/hospitals/recommend'
    | '/api/medicines/$id'
    | '/api/medicines/by-symptom'
    | '/api/medicines/search'
    | '/api/reminders/daily'
    | '/_authenticated/explore/'
    | '/api/medicines/'
    | '/_authenticated/explore/medicines/$id'
    | '/_authenticated/explore/symptoms/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiHospitalsNearbyRoute: typeof ApiHospitalsNearbyRoute
  ApiHospitalsRecommendRoute: typeof ApiHospitalsRecommendRoute
  ApiMedicinesIdRoute: typeof ApiMedicinesIdRoute
  ApiMedicinesBySymptomRoute: typeof ApiMedicinesBySymptomRoute
  ApiMedicinesSearchRoute: typeof ApiMedicinesSearchRoute
  ApiRemindersDailyRoute: typeof ApiRemindersDailyRoute
  ApiMedicinesIndexRoute: typeof ApiMedicinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/explore/': {
      id: '/_authenticated/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof AuthenticatedExploreIndexRouteImport
      parentRoute: typeof AuthenticatedExploreRouteRoute
    }
    '/_authenticated/explore/hospitals': {
      id: '/_authenticated/explore/hospitals'
      path: '/hospitals'
      fullPath: '/explore/hospitals'
      preLoaderRoute: typeof AuthenticatedExploreHospitalsRouteImport
      parentRoute: typeof AuthenticatedExploreRouteRoute
    }
    '/api/hospitals/nearby': {
      id: '/api/hospitals/nearby'
      path: '/api/hospitals/nearby'
      fullPath: '/api/hospitals/nearby'
      preLoaderRoute: typeof ApiHospitalsNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hospitals/recommend': {
      id: '/api/hospitals/recommend'
      path: '/api/hospitals/recommend'
      fullPath: '/api/hospitals/recommend'
      preLoaderRoute: typeof ApiHospitalsRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medicines/': {
      id: '/api/medicines/'
      path: '/api/medicines'
      fullPath: '/api/medicines/'
      preLoaderRoute: typeof ApiMedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medicines/$id': {
      id: '/api/medicines/$id'
      path: '/api/medicines/$id'
      fullPath: '/api/medicines/$id'
      preLoaderRoute: typeof ApiMedicinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medicines/by-symptom': {
      id: '/api/medicines/by-symptom'
      path: '/api/medicines/by-symptom'
      fullPath: '/api/medicines/by-symptom'
      preLoaderRoute: typeof ApiMedicinesBySymptomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medicines/search': {
      id: '/api/medicines/search'
      path: '/api/medicines/search'
      fullPath: '/api/medicines/search'
      preLoaderRoute: typeof ApiMedicinesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/daily': {
      id: '/api/reminders/daily'
      path: '/api/reminders/daily'
      fullPath: '/api/reminders/daily'
      preLoaderRoute: typeof ApiRemindersDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/explore/medicines/$id': {
      id: '/_authenticated/explore/medicines/$id'
      path: '/medicines/$id'
      fullPath: '/explore/medicines/$id'
      preLoaderRoute: typeof AuthenticatedExploreMedicinesIdRouteImport
      parentRoute: typeof AuthenticatedExploreRouteRoute
    }
    '/_authenticated/explore/symptoms/$name': {
      id: '/_authenticated/explore/symptoms/$name'
      path: '/symptoms/$name'
      fullPath: '/explore/symptoms/$name'
      preLoaderRoute: typeof AuthenticatedExploreSymptomsNameRouteImport
      parentRoute: typeof AuthenticatedExploreRouteRoute
    }
  }
}

interface AuthenticatedExploreRouteRouteChildren {
  AuthenticatedExploreHospitalsRoute: typeof AuthenticatedExploreHospitalsRoute
  AuthenticatedExploreIndexRoute: typeof AuthenticatedExploreIndexRoute
  AuthenticatedExploreMedicinesIdRoute: typeof AuthenticatedExploreMedicinesIdRoute
  AuthenticatedExploreSymptomsNameRoute: typeof AuthenticatedExploreSymptomsNameRoute
}

const AuthenticatedExploreRouteRouteChildren: AuthenticatedExploreRouteRouteChildren =
  {
    AuthenticatedExploreHospitalsRoute: AuthenticatedExploreHospitalsRoute,
    AuthenticatedExploreIndexRoute: AuthenticatedExploreIndexRoute,
    AuthenticatedExploreMedicinesIdRoute: AuthenticatedExploreMedicinesIdRoute,
    AuthenticatedExploreSymptomsNameRoute:
      AuthenticatedExploreSymptomsNameRoute,
  }

const AuthenticatedExploreRouteRouteWithChildren =
  AuthenticatedExploreRouteRoute._addFileChildren(
    AuthenticatedExploreRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExploreRouteRoute: typeof AuthenticatedExploreRouteRouteWithChildren
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExploreRouteRoute: AuthenticatedExploreRouteRouteWithChildren,
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiHospitalsNearbyRoute: ApiHospitalsNearbyRoute,
  ApiHospitalsRecommendRoute: ApiHospitalsRecommendRoute,
  ApiMedicinesIdRoute: ApiMedicinesIdRoute,
  ApiMedicinesBySymptomRoute: ApiMedicinesBySymptomRoute,
  ApiMedicinesSearchRoute: ApiMedicinesSearchRoute,
  ApiRemindersDailyRoute: ApiRemindersDailyRoute,
  ApiMedicinesIndexRoute: ApiMedicinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
